---
- name: traefik directories present
  become: true
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ traefik_dir }}'

- name: acme.json config file exists
  become: true
  file:
    path: '{{ traefik_dir }}/acme.json'
    state: touch
    mode: 0600
  changed_when: false

- name: template traefik.yml configs file
  become: true
  template:
    force: true
    src: ../templates/traefik.yml.j2
    dest: '{{ traefik_dir }}/traefik.yml'
    mode: 0600

- name: template traefik's middleware configs file
  become: true
  template:
    force: true

- name: create traefik administered docker internal network
  become: true
  docker_network:
    name: '{{ traefik_docker_network }}'
    internal: false

- name: traefik docker container
  become: true
  docker_container:
    name: traefik
    image: '{{ traefik_docker_image }}'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - name: '{{ traefik_docker_network }}'
    purge_networks: true
    networks_cli_compatible: true
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '{{ traefik_dir }}/traefik.yml:/traefik.yml'
      - '{{ traefik_dir }}/acme.json:/acme.json'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.entrypoints: 'http'
      traefik.http.routers.traefik.rule: 'Host(`{{ traefik_api_url }}`)'
      traefik.http.middlewares.traefik-auth.basicauth.users:
        '{{ traefik_admin_encrypted_passwd }}'
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme:
        https
      traefik.http.routers.traefik.middlewares: 'traefik-https-redirect'
      traefik.http.routers.traefik-secure.entrypoints: 'https'
      traefik.http.routers.traefik-secure.rule: 'Host(`{{ traefik_api_url }}`)'
      traefik.http.routers.traefik-secure.middlewares: 'traefik-auth'
      traefik.http.routers.traefik-secure.tls: 'true'
      traefik.http.routers.traefik-secure.tls.certresolver: 'http'
      traefik.http.routers.traefik-secure.service: 'api@internal'
      # OLD
      # traefik.enable: 'true'
      # traefik.backend: '{{ traefik_api_entrypoint }}'
      # traefik.backend: 'traefik'
      # traefik.frontend.rule: 'Host:{{ traefik_api_url }}'
      # traefik.port: '{{ traefik_api_port }}'
    restart_policy: unless-stopped
