---
- name: traefik directories present
  become: true
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ traefik_data_directory }}'

- name: create traefik administered docker internal network
  become: true
  docker_network:
    name: 'web'
