---
dependency:
  name: galaxy
  ignore-certs: True
  ignore-errors: True
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8888"
      - "vm.network 'forwarded_port', guest: 12345, host: 12345"
      - "vm.network 'private_network', ip: '192.168.99.13'"
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
